	
<?php
    $_helper = $this->helper('catalog/output');
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
?>


<div class="content">
		<div class="tabset1">
			<div data-pws-tab="tab1" data-pws-tab-name="<?php echo Mage::getModel('catalog/category')->load(206)->getName() ?>">

			
			
			
<div class="category-products">


	<?php 
	$categoryId = 206;
	$_category = Mage::getModel('catalog/category')->load($categoryId);
	$categoryName = $_category->getName();
	$_productCollection = Mage::getSingleton('catalog/category')->load($categoryId)
				->getProductCollection()
				->addAttributeToSelect('*');
	?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php //$_columnCount = Mage::getStoreConfig('legenda_setting/category_grid/columns', $code); ?>    
    <?php  $_columnCount = Mage::helper('legenda')->getCategoryColumns($code); ?>
    <ul class="products-grid column5 row">
    <?php foreach ($_productCollection as $_product): ?>
            <li class="item">
                <div class="item-area">
                    <div class="product-image-wrapper <?php if (Mage::getStoreConfig('legenda_setting/category/effect_img', $code) && !Mage::helper('configurableswatches')->isEnabled()): ?>hover-effect-slider<?php endif; ?>">
                    <?php 
                        // Get the Special Price
                        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
                        // Get the Special Price FROM date
                        $specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
                        // Get the Special Price TO date
                        $specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
                        // Get Current date
                        $today =  time();
                     
                        if ($specialprice){
                            if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)){
                                if(Mage::getStoreConfig("legenda_setting/product_label/sale", $code)){
                    ?>
                                <span class="label-icon sale-label">Sale!</span>
                    <?php       
                                }
                            }
                        }
                    ?>
                    <?php
                        $now = date("Y-m-d");
                        $newsFrom= substr($_product->getData('news_from_date'),0,10);
                        $newsTo=  substr($_product->getData('news_to_date'),0,10);
                        if ($newsTo != '' || $newsFrom != ''){
                            if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo))
                            {
                                if(Mage::getStoreConfig("legenda_setting/product_label/new", $code)){
                        ?> 
                                <span class="label-icon new-label second-label">New</span>
                        <?php 
                                }
                            }
                        }
                    ?>
                    <?php 
                        $imgList = ''; 
                        if (Mage::getStoreConfig('legenda_setting/category/effect_img', $code)) {
                            $product = Mage::getModel('catalog/product')->load($_product->getId());
                            foreach ($product->getMediaGalleryImages() as $image) {
                                // If no image, skip 
                                if ($image->getFile() == NULL)
                                    continue;
                                if (Mage::getStoreConfig('legenda_setting/category/aspect_ratio', $code)) {
    //                                $imgList .= Mage::helper('catalog/image')->init($_product, 'thumbnail', $image->getFile()).',';
                                    $imgList .= Mage::helper('catalog/image')->init($_product,'thumbnail',$image->getFile())->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(350).',';   
                                } else {
                                    $imgWidth = Mage::getStoreConfig('legenda_setting/category/ratio_width', $code);
                                    $imgHeight = Mage::getStoreConfig('legenda_setting/category/ratio_height', $code);
                                    $imgList .= Mage::helper('catalog/image')->init($_product,'thumbnail',$image->getFile())->resize($imgWidth, $imgHeight).',';
                                }
                            }
                            $imgList = substr($imgList, 0, strlen($imgList) - 1);
                        }
                    ?>
                    <?php if(!$_product->isSaleable()): ?>
                        <span class="out-of-stock"><?php echo $this->__('Out of stock') ?></span>
                    <?php endif; ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" data-images-list="<?php echo $imgList; ?>">
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php if(Mage::getStoreConfig('legenda_setting/category/aspect_ratio', $code)):?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(350); ?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(Mage::getStoreConfig('legenda_setting/category/ratio_width', $code), Mage::getStoreConfig('legenda_setting/category/ratio_height', $code)); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </a> 
<?php /*?>						
						<?php if (Mage::getStoreConfig('quickview/general/enableview', $code)): ?>
						    <a href="<?php echo $_product->getId() ?>" class="sw-product-quickview"><?php echo $this->__('Quick View') ?></a>
                        <?php endif; ?>
<?php */?>
                    </div>
					<h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
                    <div class="description-wrapper">

                        <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif; ?>
                        <?php
                        // Provides extra blocks on which to hang some features for products in the list
                        // Features providing UI elements targeting this block will display directly below the product name
                        echo $this->getChildHtml('product_list.name.after');
                        if ($this->getChild('name.after')) {
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
                                echo $_nameAfterChild->toHtml();
                            }
                        }
                        ?>
                        <?php echo $this->getPriceHtml($_product, true) ?>

                        <div class="actions">
						  <div class="buy-buttons"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="buy button btn-cart btn-cart-<?php echo $_product->getId()?>" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></div>
							<div class="buy-buttons"><button type="button" title="Купить со скидкой" class="buy-discount button btn-cart btn-cart-<?php echo $_product->getId()?>" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span>Купить со скидкой</span></span></button></div>
<?php /*?>		
                        <?php if(Mage::getStoreConfig('ajaxcart/addtocart/enablecategory')): ?>
                            <?php if($_product->isSaleable()): ?>
                                <?php  if ( !($_product->getData('has_options') || $_product->isGrouped()) ) :  ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart btn-cart-<?php echo $_product->getId()?>" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php else: ?>
                                    <button type="button" title="<?php echo $this->__('Select Option') ?>" class="button btn-cart btn-cart-<?php echo $_product->getId()?>" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Select Option') ?></span></span></button>
                                    <a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Options</a>
                                <?php endif; ?>
							<?php else: ?>
								<a href="<?php echo $_product->getProductUrl() ?>" class="button"><?php echo $this->__('Read More') ?></a>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php if($_product->isSaleable()): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php endif; ?>
                        <?php endif; ?>
                        
                        <?php if(Mage::getStoreConfig('ajaxcart/addtolinks/enablecategory')): ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="#" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>","<?php echo $_product->getId()?>");return false;' class="link-wishlist link-wishlist-<?php echo $_product->getId()?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <li><span class="separator">|</span> <a href="#" onclick='ajaxCompare("<?php echo $_compareUrl ?>","<?php echo $_product->getId()?>");return false;' class="link-compare link-compare-<?php echo $_product->getId()?>"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>                        
                            </ul>
                        <?php else: ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist button"></a></li>
                                <?php endif; ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <li><a href="<?php echo $_compareUrl ?>" class="link-compare button"></a></li>
                                <?php endif; ?>
                            </ul>
<?php */?>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
    </ul>
        <script type="text/javascript">
            jQuery('.col-main .products-grid li:nth-child(2n)').addClass('nth-child-2n');
            jQuery('.col-main .products-grid li:nth-child(2n+1)').addClass('nth-child-2np1');
            jQuery('.col-main .products-grid li:nth-child(3n)').addClass('nth-child-3n');
            jQuery('.col-main .products-grid li:nth-child(3n+1)').addClass('nth-child-3np1');
            jQuery('.col-main .products-grid li:nth-child(4n)').addClass('nth-child-4n');
            jQuery('.col-main .products-grid li:nth-child(4n+1)').addClass('nth-child-4np1');
            jQuery('.col-main .products-grid li:nth-child(5n)').addClass('nth-child-5n');
            jQuery('.col-main .products-grid li:nth-child(5n+1)').addClass('nth-child-5np1');
        </script>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

</div>			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			
			</div>
			<div data-pws-tab="tab2" data-pws-tab-name="<?php echo Mage::getModel('catalog/category')->load(207)->getName() ?>">

			
<div class="category-products">


	<?php 
	$categoryId = 207;
	$_category = Mage::getModel('catalog/category')->load($categoryId);
	$categoryName = $_category->getName();
	$_productCollection = Mage::getSingleton('catalog/category')->load($categoryId)
				->getProductCollection()
				->addAttributeToSelect('*');
	?>
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php //$_columnCount = Mage::getStoreConfig('legenda_setting/category_grid/columns', $code); ?>    
    <?php  $_columnCount = Mage::helper('legenda')->getCategoryColumns($code); ?>
    <ul class="products-grid column5 row">
    <?php foreach ($_productCollection as $_product): ?>
            <li class="item">
                <div class="item-area">
                    <div class="product-image-wrapper <?php if (Mage::getStoreConfig('legenda_setting/category/effect_img', $code) && !Mage::helper('configurableswatches')->isEnabled()): ?>hover-effect-slider<?php endif; ?>">
                    <?php 
                        // Get the Special Price
                        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
                        // Get the Special Price FROM date
                        $specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
                        // Get the Special Price TO date
                        $specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
                        // Get Current date
                        $today =  time();
                     
                        if ($specialprice){
                            if($today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate)){
                                if(Mage::getStoreConfig("legenda_setting/product_label/sale", $code)){
                    ?>
                                <span class="label-icon sale-label">Sale!</span>
                    <?php       
                                }
                            }
                        }
                    ?>
                    <?php
                        $now = date("Y-m-d");
                        $newsFrom= substr($_product->getData('news_from_date'),0,10);
                        $newsTo=  substr($_product->getData('news_to_date'),0,10);
                        if ($newsTo != '' || $newsFrom != ''){
                            if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo))
                            {
                                if(Mage::getStoreConfig("legenda_setting/product_label/new", $code)){
                        ?> 
                                <span class="label-icon new-label second-label">New</span>
                        <?php 
                                }
                            }
                        }
                    ?>
                    <?php 
                        $imgList = ''; 
                        if (Mage::getStoreConfig('legenda_setting/category/effect_img', $code)) {
                            $product = Mage::getModel('catalog/product')->load($_product->getId());
                            foreach ($product->getMediaGalleryImages() as $image) {
                                // If no image, skip 
                                if ($image->getFile() == NULL)
                                    continue;
                                if (Mage::getStoreConfig('legenda_setting/category/aspect_ratio', $code)) {
    //                                $imgList .= Mage::helper('catalog/image')->init($_product, 'thumbnail', $image->getFile()).',';
                                    $imgList .= Mage::helper('catalog/image')->init($_product,'thumbnail',$image->getFile())->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(350).',';   
                                } else {
                                    $imgWidth = Mage::getStoreConfig('legenda_setting/category/ratio_width', $code);
                                    $imgHeight = Mage::getStoreConfig('legenda_setting/category/ratio_height', $code);
                                    $imgList .= Mage::helper('catalog/image')->init($_product,'thumbnail',$image->getFile())->resize($imgWidth, $imgHeight).',';
                                }
                            }
                            $imgList = substr($imgList, 0, strlen($imgList) - 1);
                        }
                    ?>
                    <?php if(!$_product->isSaleable()): ?>
                        <span class="out-of-stock"><?php echo $this->__('Out of stock') ?></span>
                    <?php endif; ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image" data-images-list="<?php echo $imgList; ?>">
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>" src="<?php if(Mage::getStoreConfig('legenda_setting/category/aspect_ratio', $code)):?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(350); ?><?php else: ?><?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(Mage::getStoreConfig('legenda_setting/category/ratio_width', $code), Mage::getStoreConfig('legenda_setting/category/ratio_height', $code)); ?><?php endif; ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </a> 
<?php /*?>						
						<?php if (Mage::getStoreConfig('quickview/general/enableview', $code)): ?>
						    <a href="<?php echo $_product->getId() ?>" class="sw-product-quickview"><?php echo $this->__('Quick View') ?></a>
                        <?php endif; ?>
<?php */?>
                    </div>
					<h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h3>
                    <div class="description-wrapper">

                        <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php endif; ?>
                        <?php
                        // Provides extra blocks on which to hang some features for products in the list
                        // Features providing UI elements targeting this block will display directly below the product name
                        echo $this->getChildHtml('product_list.name.after');
                        if ($this->getChild('name.after')) {
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
                                echo $_nameAfterChild->toHtml();
                            }
                        }
                        ?>
                        <?php echo $this->getPriceHtml($_product, true) ?>

                        <div class="actions">
						  <div class="buy-buttons"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="buy button btn-cart btn-cart-<?php echo $_product->getId()?>" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></div>
							<div class="buy-buttons"><button type="button" title="Купить со скидкой" class="buy-discount button btn-cart btn-cart-<?php echo $_product->getId()?>" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span>Купить со скидкой</span></span></button></div>
<?php /*?>		
                        <?php if(Mage::getStoreConfig('ajaxcart/addtocart/enablecategory')): ?>
                            <?php if($_product->isSaleable()): ?>
                                <?php  if ( !($_product->getData('has_options') || $_product->isGrouped()) ) :  ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart btn-cart-<?php echo $_product->getId()?>" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <?php else: ?>
                                    <button type="button" title="<?php echo $this->__('Select Option') ?>" class="button btn-cart btn-cart-<?php echo $_product->getId()?>" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Select Option') ?></span></span></button>
                                    <a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Options</a>
                                <?php endif; ?>
							<?php else: ?>
								<a href="<?php echo $_product->getProductUrl() ?>" class="button"><?php echo $this->__('Read More') ?></a>
                            <?php endif; ?>
                        <?php else: ?>
                            <?php if($_product->isSaleable()): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php endif; ?>
                        <?php endif; ?>
                        
                        <?php if(Mage::getStoreConfig('ajaxcart/addtolinks/enablecategory')): ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="#" onclick='ajaxWishlist("<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>","<?php echo $_product->getId()?>");return false;' class="link-wishlist link-wishlist-<?php echo $_product->getId()?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <li><span class="separator">|</span> <a href="#" onclick='ajaxCompare("<?php echo $_compareUrl ?>","<?php echo $_product->getId()?>");return false;' class="link-compare link-compare-<?php echo $_product->getId()?>"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>                        
                            </ul>
                        <?php else: ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist button"></a></li>
                                <?php endif; ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <li><a href="<?php echo $_compareUrl ?>" class="link-compare button"></a></li>
                                <?php endif; ?>
                            </ul>
<?php */?>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
    </ul>
        <script type="text/javascript">
            jQuery('.col-main .products-grid li:nth-child(2n)').addClass('nth-child-2n');
            jQuery('.col-main .products-grid li:nth-child(2n+1)').addClass('nth-child-2np1');
            jQuery('.col-main .products-grid li:nth-child(3n)').addClass('nth-child-3n');
            jQuery('.col-main .products-grid li:nth-child(3n+1)').addClass('nth-child-3np1');
            jQuery('.col-main .products-grid li:nth-child(4n)').addClass('nth-child-4n');
            jQuery('.col-main .products-grid li:nth-child(4n+1)').addClass('nth-child-4np1');
            jQuery('.col-main .products-grid li:nth-child(5n)').addClass('nth-child-5n');
            jQuery('.col-main .products-grid li:nth-child(5n+1)').addClass('nth-child-5np1');
        </script>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>

</div>				
			
			
			
			
			
			
			
			
			
			
			
			</div>
		</div><!-- tabset1 -->
      
</div><!-- content -->
<script>
jQuery(document).ready(function ($) {
	$('.tabset1').pwstabs();

});
</script>